@startuml

class Dummy {
  - private
  # protected
  ~ pkg method()
  + public()
}  /' Legend Dummy ;D '/

Interface User {
  # createAccount(AccountType)
  # login()
  # logout()
}

class Admin {
  # createService()
  # removeAccount()
  # removeAccount()

  # setHourlyRate()
  # setForm(Service.type, customerInfo)
}
class Employee {
  # createAccount(Employee)
  # selectService()
  # setBusinessHour()
  # boolean processServiceRequest()

  # notifyCustomer()
}
class Customer {
  # createAccount(Customer)

  # searchBranch()
  # selectService()
  # getForm(Service.type).fill()
  # submitForm()

  # rateBranch()
}
User <|-- Admin
User <|-- Employee
User <|-- Customer


' ------------------------------------------
Interface Form {
  # firstName
  # lastName
  # dateOfBirth
  # address
  # email
}
abstract RentalForm {
  # pickupTime
  # returnTime
  # licenseType
}
Form <|-- RentalForm

class carRentalForm {
  # carType
}
class truckRentalForm {
  # usageArea
}
class MovingForm {
  # startLocation
  # endLocation
  # numberOfMovers
  # numberOfBoxes
}

RentalForm <|-- carRentalForm
RentalForm <|-- truckRentalForm
Form <|-- MovingForm

@enduml